from datetime import datetime
def generate_Sell_bills():
           file.write("Customer_name:"+ str(customer_name))
           file.write("-----------------------------------------------------")
           file.write("/n")
           file.write("Product id\t Product name\t Selling_price\tquantity\t brand\ttt Total")
           file.write("\n")
           file.write("Product id :" + str(Product_id)+"\n")
           file.write(str(Product_id) + "\t" + str(name_of_product) + "\t" + str(Selling_price) +
                   "\t" + str(quantity) + "\t" + str(brand) + "\t" + str(Total_with_vat) + "\n")
           file.write("\n")
           file.write("--------------------------------------------")           
           file.write("Total VAT(13%):$" +str(Total_with_vat))
           file.write("Free Items: " + str(free_items) + " free\n")
           file.write("\n")        
           file.write("\n")
           file.write("-------------------------------------------------------------------")
           file.write("\n")
           file.write("\n")
           print("Sell bill generated")
def generate_Buy_bills():
    
           file.write("Name of manufacturer:"+ str(name_of_manufacturer))
           file.write("-----------------------------------------------------")
           file.write("/n")
           file.write("Product id\t Product name\t Cost price\tquantity\t brand\t Total")
           file.write("\n")
           file.write("Product id :" + str(Product_id))
           file.write("\n")
           file.write("..................."*5)
           file.write("Product name :" + str(name_of_product))
           file.write("........................"*5)
           file.write("\n")
           file.write("Quantity:" + str(quantity))
           file.write(".................."*5)
           file.write("\n")
           file.write("Origin:" + str(Origin))
           file.write("................"*5)           
           file.write("Total VAT(13%):$" +str(Total_amount))
           file.write(".................."*5)
           file.write("\n")        
           file.write("\n")
           file.write("-------------------------------------------------------------------")
           file.write("\n")
           print("Buy bill generated")
                      
